scalar Date

#Entry points
extend type Query {
  employees: [Employee]!
  employee(id: ID!): Employee!
}

type Employee {
  id: ID!
  firstName: String!
  lastName: String!
  role: String!
  email: String!
  phoneNumber: String!
  timeEntries: [TimeEntry]!
}

input CreateEmployeeInput {
  firstName: String!
  lastName: String!
  role: String!
  email: String!
  phoneNumber: String!
}

type Mutation {
  createEmployee(newEmployee: CreateEmployeeInput): Employee!
  updateEmployee(id: ID!, updatedEmployee: CreateEmployeeInput): Employee!
}
