scalar Date

extend type Query {
  employees: [Employee]!
  #employees(pagination: PaginationInput): EmployeesPage!
  employee(id: ID!): Employee!
}

type Employee {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  phoneNumber: String!
  timeEntries: [TimeEntry]!
}

input CreateEmployeeInput {
  firstName: String!
  lastName: String!
  email: String!
  phoneNumber: String!
}

type Mutation {
  createEmployee(newEmployee: CreateEmployeeInput): Employee!
  updateEmployee(id: ID!, updatedEmployee: CreateEmployeeInput): Employee!
}

input PaginationInput {
  page: Int!
  perPage: Int!
}

type PaginationResponse {
  page: Int!
  perPage: Int!
  totalCount: Int!
}

type EmployeesPage {
  pagination: PaginationResponse!
  employees: [Employee]!
}
