# employee.schema.graphql

scalar Date

extend type Query {
  employees: [Employee]!
  employee(id: ID!): Employee!

  # Hent alle medarbejdere med pagination
  #employees(pagination: PaginationInput!): EmployeesPage!
}

# type Query {
#   employees: [Employee]!
#   employee(id: ID!): Employee!
#   employees(pagination: PaginationInput!): EmployeesPage!
# }

type Employee {
  id: ID!
  firstName: String!
  lastName: String!
  role: String!
  email: String!
  phoneNumber: String!
  timeEntries: [TimeEntry]!
}

input PaginationInput {
  page: Int!
  perPage: Int!
}

type PaginationResponse {
  page: Int!
  perPage: Int!
  totalCount: Int!
}

type EmployeesPage {
  pagination: PaginationResponse!
  items: [Employee]!
}

type Mutation {
  createEmployee(newEmployee: CreateEmployeeInput): Employee!
  updateEmployee(id: ID!, updatedEmployee: CreateEmployeeInput): Employee!
}

input CreateEmployeeInput {
  firstName: String!
  lastName: String!
  role: String!
  email: String!
  phoneNumber: String!
}
