scalar Date
scalar Unix
scalar Time

type Mutation {
  createEmployee(newEmployee: CreateEmployeeInput): CreatedEmployee!
  updateEmployee(id: ID!, updatedEmployee: CreateEmployeeInput): Employee!
  handleEmployeeLogin(loginInput: LoginInput!): Employee!

  createTimeEntry(newTimeEntry: CreateTimeEntryInput): TimeEntry!
  deleteTimeEntry(id: ID!): ID!
  updateTimeEntry(id: ID!, updatedTimeEntry: TimeEntryInput!): TimeEntry
  updateTimeEntryStatus(notification: NotificationStatusInput!): Notification!
}
