scalar Date
scalar Unix
scalar Time

type Query {
  employee(id: ID!): Employee!
  employees(search: String): [Employee]!
  
  filteredEmployees(filter: EmployeeFilterInput, sort: SortInput): [Employee]!

  paginatedEmployees(
  pagination: PaginationInput!
  search: String
  roles: [String!]
  permissions: [String!]
  sort: SortInput
): PaginatedEmployeesResponse!

  notification(id: ID!): Notification!
  notifications: [Notification]!

  timeEntry(id: ID!): TimeEntry!
  timeEntries(search: String): [TimeEntry]!
  timeEntriesForEmployee(employeeId: ID!, search: String, sort: SortInput): [TimeEntry]!

  roles: [Role]!
  permissions: [Permission]!

  userMenuLinks(employeeId: Int!): [UserMenuLink!]!
}
