scalar Date
scalar Unix
scalar Time

type Query {
  employee(id: ID!): Employee!
  employees(search: String): [Employee]!
  
  filteredEmployees(filter: EmployeeFilterInput): [Employee]!

  paginatedEmployees(
  pagination: PaginationInput!
  search: String
  roles: [String!]
  permissions: [String!]
): PaginatedEmployeesResponse!

  notification(id: ID!): Notification!
  notifications: [Notification]!

  timeEntry(id: ID!): TimeEntry!
  timeEntries: [TimeEntry]!

  roles: [Role]!
  permissions: [Permission]!

  userMenuLinks(employeeId: Int!): [UserMenuLink!]!

  # employees(
  #   search: String
  #   order: String
  #   orderBy: String
  #   limit: Int
  #   offset: Int
  #   pagination: PaginationInput!
  #   roleName: [Int!]
  #   permissionLevel: [Int!]
  #   ):[Employee]!

  # paginatedEmployees(
  #   search: String
  #   orderBy: String
  #   order: String
  #   pagination: PaginationInput!
  #   employee: [Int]
  # ): PaginatedEmployeesResponse!

}
