scalar Date
scalar Unix
scalar Time

type Query {
  employee(id: ID!): Employee!
  employees: [Employee]!
  filteredEmployees(filter: EmployeeFilterInput, search: String): [Employee]!
  # employees(
  #   orderBy: String
  #   order: OrderDirection
  #   employeeRole: [String!]
  #   employeePermission: [String!]
  # ): [Employee!]!

  #employees(pagination: PaginationInput): EmployeesPage!

  notification(id: ID!): Notification!
  notifications: [Notification]!

  timeEntry(id: ID!): TimeEntry!
  timeEntries: [TimeEntry]!

  roles: [Role]!
  permissions: [Permission]!

  userMenuLinks(employeeId: Int!): [UserMenuLink!]!
}
