scalar Date
scalar Time
scalar Unix

# TYPES
type TimeEntry {
  id: ID!
  startTime: Time!
  endTime: Time
  duration: String
  comment: String
  startDate: Date!
  endDate: Date
  employee: Employee
  notification: Notification!
  #employeeID: ID
}

type TimeEntryStatus {
  id: ID!
  notification: Notification!
}

# Queries - ENTRY POINTS
extend type Query {
  timeEntries: [TimeEntry]!
  timeEntry(id: ID!): TimeEntry!
}

# INPUT
input CreateTimeEntryInput {
  startTime: Time!
  endTime: Time
  duration: String
  comment: String
  startDate: Date!
  endDate: Date
  notification: NotificationInput!
  employeeID: ID!
}

input NotificationStatusInput {
  id: ID!
  status: String
}

# MUTATIONS
type Mutation {
  createTimeEntry(newTimeEntry: CreateTimeEntryInput): TimeEntry!
}

extend type Mutation {
  updateTimeEntryStatus(notification: NotificationStatusInput!): Notification!
}
