scalar Date
scalar MyTimeStamp

type TimeEntry {
  id: ID!
  startTime: MyTimeStamp!
  endTime: MyTimeStamp!
  duration: String!
  comment: String
  date: Date!
  notification: Notification!
  employeeID: ID
}

type Notification {
  id: ID!
  comment: String
  timestamp: MyTimeStamp
  status: String
}

#Entry points
extend type Query {
  timeEntries: [TimeEntry]!
  timeEntry(id: ID!): TimeEntry!
}

input CreateTimeEntryInput {
  startTime: MyTimeStamp!
  endTime: MyTimeStamp!
  duration: String!
  comment: String
  date: Date!
  notification: NotificationInput!
  employeeID: ID!
  #employeeID: ID!
}

type Mutation {
  createTimeEntry(newTimeEntry: CreateTimeEntryInput): TimeEntry!
}

input NotificationInput {
  comment: String
  timestamp: MyTimeStamp!
  status: String!
}
