scalar Date
scalar Time

type TimeEntry {
  id: ID!
  startTime: Time
  endTime: Time
  duration: String
  comment: String
  date: Date
  status: String
  firstName: String
  lastName: String
  notification: Notification!
  employeeID: ID
}

#Entry points
extend type Query {
  timeEntries: [TimeEntry]!
  timeEntry(id: ID!): TimeEntry!
}

input CreateTimeEntryInput {
  startTime: Time!
  endTime: Time!
  duration: String!
  comment: String
  date: Date!
  notification: NotificationInput!
  employeeID: ID!
}

type Mutation {
  createTimeEntry(newTimeEntry: CreateTimeEntryInput): TimeEntry!
}

input NotificationInput {
  comment: String
  timestamp: String
  status: String!
}

extend type Mutation {
  updateTimeEntryStatus(id: ID!, status: String!): TimeEntry!
}

type Notification {
  id: ID!
  comment: String
  timestamp: String
  status: String!
}
